Add new functionality for profile
KGG-Dev-Course/taskmaster-api pull request #24
Opened 2023-12-25 14:16 UTC by chenxidev1129

2023-12-25 14:22 UTC, kgg0305 commented
@chenxidev1129 How did you manage to authenticate the user?

2023-12-25 14:22 UTC, chenxidev1129 commented
> @chenxidev1129 How did you manage to authenticate the user?

`var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;`

I implemented this code for that.

2023-12-25 14:24 UTC, chenxidev1129 commented
@johnsmith0305 @fullstackdev0305 Who can review this PR?

2023-12-26 02:43 UTC, johnsmith0305 requested changes
We need to create new endpoint to upload profile image.

2023-12-26 10:16 UTC, johnsmith0305 commented
We need to create a new endpoint to show image with image file name.

2023-12-26 13:06 UTC, chenxidev1129 commented
@johnsmith0305 I fixed all

2023-12-26 13:10 UTC, johnsmith0305 requested changes

2023-12-26 13:10 UTC, johnsmith0305 commented on taskmaster-api/Services/Interface/IProfileService.cs
> +using Microsoft.AspNetCore.Mvc;
I am not sure why this is used

2023-12-26 13:16 UTC, smartwebdev2023 commented
I formatted/refactored some code.

2023-12-26 13:18 UTC, smartwebdev2023 approved these changes

2023-12-26 13:20 UTC, johnsmith0305 approved these changes

2023-12-26 13:20 UTC, fullstackdev0305 approved these changes

2023-12-26 13:20 UTC, merged